on:
  push:
    branches:
      - production
      
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup SSH
        run: |
          whoami
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 213.148.21.83 >> ~/.ssh/known_hosts
          
      - name: Deploy files to server
        run: |
          rsync -avz --delete ./ root@213.148.21.83:/home/mdev/travel_front
          
          

